broadinstitute/horsefish

scripts/update_workspace_dd.py
* Adds new buckets involved in migration to bucket list
* Alters predicate to identify paths to update to correctly mark BAI and MD5 files for update
* Removes regex parsing logic from lookup tool - new mapping is now a direct path-to-path lookup
=> Alter workspace update script to use new mapping, handle BAIs/MD5s

scripts/update_workspace_dd.py
We've seen cases where users are trying to map paths pointing at the reduced version of a bam which has since been cleaned up. Since we can't build a comprehensive list of all possible bam varieties that might have been in a directory, I instead introduced this system to try mapping other variations of the path if we can't map the path they've given us.
=> Add support for mapping reduced bam paths to unreduced paths where required

scripts/README.md, scripts/terra_service_banner.py
In the event of a Service Incident related to the Terra UI, SDLC notes that a message must be posted to the platform for users to be made aware of the ongoing issue. The messaging is provided to users of the platform with a modifiable banner.The process of posting the banner has a few steps that are manual but this python script provides a streamlined solution for internal members that are on a suitability roster.
=> [DFE-2781] add + remove terra service banner

scripts/launch_workflow_cf/README.md, scripts/launch_workflow_cf/config.yaml, scripts/launch_workflow_cf/deploy_cloud_function.sh, scripts/launch_workflow_cf/example.tsv, scripts/launch_workflow_cf/example.wdl, scripts/launch_workflow_cf/main.py, scripts/launch_workflow_cf/requirements.txt, scripts/launch_workflow_cf/test_cloud_function.sh, scripts/launch_workflow_cf/utils.py
Also:
* added an example WDL and entity set to provide more context
* allow users to specify which entity set to use
* facilitate faster testing by authenticating locally as the service account
* refactor more of what was in main into utils
* rename parameters for clarity
* add pydocs
=> Expand the setup instructions for the Cloud Functions example.

scripts/set_requester_pays.sh
usage:
```
✗ ./set_requester_pays.sh
Usage: ./set_requester_pays.sh PROJECT_ID gs://BUCKET1 [gs://BUCKET2 gs://BUCKET3...]
NOTE: this script requires you to be authed as your firecloud.org admin account.
```
works like this:
```
✗ ./set_requester_pays.sh anvil-datastorage gs://fc-secure-d72b37f0-4431-48bf-b8f0-95b745deadbc
Your active configuration is: [new]
Enabling permissions for marymorg@firecloud.org to switch on Requester Pays
Updated IAM policy for project [anvil-datastorage].
- members:
- user:marymorg@firecloud.org
role: projects/anvil-datastorage/roles/RequesterPays
Gatorcounting for 20 seconds while iam change goes into effect
NOTE: if you get an error message saying:
AccessDeniedException: 403 marymorg@firecloud.org does not have storage.buckets.update access to the Google …
```
=> make script to set requester pays on a Terra bucket - DFE-376

scripts/set_requester_pays.sh
the change is to add an organization-wide role, "RequesterPaysToggler", that lives in the firecloud.org organization, that can be used with any project inside that org. the previous role used in this script wasn't available in all Terra projects and resulted in an error.
also decreased the wait time, since it'll involve manual re-running pretty much no matter what.
=> update to Requester Pays script: use org-wide role that works for all projects

scripts/terra_service_banner.py
Jason mentioned that its easier for Frontline to post banners by passing in a json file instead of putting strings as individual arguments for the components of the banner. Implemented a small addition to allow for passing in a json and then posting the banner.
=> [DFE-413] allow user to pass in json instead of separate args

scripts/van_allen_tools/set_up_vanallen_workspaces.py
This pull request is for some minor changes to `scripts/van_allen_tools/set_up_vanallen_workspaces.py`, changing the input args to match those being passed to the `setup_workspaces` function. Specifically, the language was standardized to refer to namespaces instead of projects. 
It works great otherwise! I used the script to successfully create and share permissions for two new regional workspaces
```
(horsefish) (base) breardon@blueberry:van_allen_tools$ python set_up_vanallen_workspaces.py -t workspaces.txt -n vanallen-firecloud-nih
Successfully created workspace with name: SK_Ted_Rectal2_regional.
Successfully updated vanallen-firecloud-nih/SK_Ted_Rectal2_regional with the following user(s)/group(s): ['GROUP_vanallenlab@firecloud.org', 'breardon@broadinstitute.org', …
```
=> Changed input args to match those being passed.

scripts/terra_service_banner.py
In the old version:
```    
if args.delete:
clear_service_banner(args.env)
if args.json:
banner = convert_service_banner_json(args.json)
else:
banner = build_service_banner(args.title, args.message, args.link)
update_service_banner(args.env, banner)
```
when the if/else about json args was added, the final call to `update_service_banner` was moved out of its if/else block.  so we were ALWAYS calling `update_service_banner`, whether we were putting it up or deleting it.  so in the case when delete was true, we called `clear_service_banner` (thus deleting the banner) and then just called `update_service_banner` again, thus putting it back up.
what we want to make sure happens is that the final call to update is an if/else: if delete is true, we call `clear_service_banner` only, otherwise we …
=> fix banner so it doesn't post twice

scripts/anvil_tools/README.md, scripts/anvil_tools/add_user_to_workspace.py
The script was updated to no longer accept a project - the project information is now parsed from a column in the input tsv. The script comments as well as readme were not updated to reflect the new format - fixed this now and tested with Candace.
=> edit readme and script to remove references to project parameter

scripts/anvil_tools/README.md, scripts/anvil_tools/batch_upsert_entities_standard.py, scripts/anvil_tools/batch_usert_entities_standard.py, scripts/anvil_tools/convert_string_to_array_unit_test.py, scripts/anvil_tools/split_and_push_data_model_tsvs.py
Description:
AnVIL collaborators will submit a single tsv file containing data they want uploaded as tables to workspaces. There will be two columns labeled as `workspace_name` and `workspace_project` PER row - multiple rows can have the same combination of workspace and project information. This just means that the entire set of rows will be uploaded to the same workspace.
The script parses on the unique combination of `workspace_name` and `workspace_project` --> subsets the large tsv file into smaller tsv files, representative of a single workspace's data table contents --> calls  functions from `batch_upsert_entities_standard.py` to create the json request PER subsetted tsv --> loads the table to its respective workspace.
Tests:
1. `convert_string_to_array_unit_test.py` will check that …
=> [DFE-524] split large tsv file by workspace and project columns and push subset tsv to terra data model

scripts/anvil_tools/README.md, scripts/anvil_tools/gather_and_concatenate_data_model_tsvs.py, scripts/anvil_tools/split_and_push_data_model_tsvs.py
From a previous script - `split_and_push_data_model_tsvs.py` - a single file formatted as a Terra load table contains extra columns for workspace name and workspace project. Using this information, the single file is split and then uploaded as the appropriate table in its correct workspace.
This script does the opposite - gathers the given entity table from each of the workspaces listed and concatenates them into the format that is input into `split_and_push_data_models.py`.
A single excel file is input and a single excel file is output - the output excel file has two sheets where one is the list of workspaces that may have failed and the second is a single load tsv table format that represents the input of the script mentioned above.
=> [DFE-594] get a single entity table from a list of workspaces and concatenate together into an excel report

scripts/terra_service_banner.py
The page location was changed by User Ed, old link no longer works.
=> update default link of service notifications page in service banner

scripts/terra_service_banner.py
Removing "private" seems to allow for immediate changes to the banner.
=> Update terra_service_banner.py to allow for immediate changes

scripts/terra_service_banner.py
The old DEFAULT_LINK points to the 2021 Service Notifications page.
The new DEFAULT_LINK points to the 2022 Service Notifications page.
=> Updating the DEFAULT_LINK for 2022

scripts/tdr/twisttcap/export_pipeline_outputs_to_tdr.py
I had misunderstood the new "updateStrategy": "replace" functionality in TDR ingest. Two major changes are implemented here:
- fix the flag from "update" (which doesn't exist, so it defaults to "append") to "replace"
- add back in the steps to pull existing data from TDR, since replace does not merge the new data with existing data
=> [DFE-736] Fix ingest workflow outputs script to use "replace" functionality

scripts/tdr/export_pipeline_outputs_to_tdr/changelog.md, scripts/tdr/export_pipeline_outputs_to_tdr/export_pipeline_outputs_to_tdr.py
meta updates:
- added a changelog to track versions
- update to version 1.2 of script/docker
functional updates:
- add option to specify multiple custom fields for a "now" timestamp
- use array/records ingest mode to avoid needing a staging bucket
- improve error handling if ingest API call fails
this has been tested with the Twist-TCAP pipeline, with corresponding WDL changes in this PR: https://github.com/broadinstitute/warp/pull/711
=> Updates to pipeline outputs to TDR, for Twist-TCAP

scripts/mop_workspace/mop_workspace.py
Our more scaleable version of mop (in mmt_add_mop branch of horsefish repo) only looks in the old submissions directories, i.e. `gs://bucket/submissionid/...`, but Terra now stores submissions in a new format: `gs://bucket/submissions/submissionid/...` so we're now missing files from recent submissions and failing to clean them up.
This PR updates the code to look in both places
=> [DFE-790] update mop to support submissions path

scripts/rare-x/ingest_rarex_dataset.py
Problem:
RARE-X datasets have ~64 tables that are ingested with data from new-line delimited json files. The json files are generated by a third-party company and put into a GCP bucket for RARE-X team to ingest. Currently, someone on the RARE-X team manually ingests each table separately. 
Solution:
Script that will take GCS storage path pointing to .json files and ingest each json to its respective table in the TDR dataset. the .json files are named [table_name].json.
=> ingest json files from bucket to respective tdr dataset tables

scripts/anvil_tools/gsutil_bucket_sync.py
Script to sync between a source google bucket (aka staging) and a destination google bucket (aka production). 
Takes in a tab-delimited file with a header and two columns: 'Destination directory' and 'Source directory'.
It runs gsutil rsync for each pair of folders, copying all changed files from destination to source.
I'll be writing up a FE ticket to create a ops portal workflow that does this (so PjMs can take over this part of the ingest workflow completely), but this is a prototype/can be used ad hoc in the meantime.
=> [AT-412] Multi-bucket rsync script

pipelines/emerge/RetryPrsSubmissionFailures.changelog.md, pipelines/emerge/retry_prs_submission_failures.wdl, scripts/emerge/retry_wfl_submission_failures.py
1. Pass in the submission id containing failed PRS workflows
2. Script will gather all failed workflows in a given submission and the entity_id - the PK - chip_well_barcode
3. use ingestDataset TDR API with the merge mode to provide the PKs
4. A re-ingest with merge should re-trigger WFL which will resubmit PRS
=> eMerge: Retry Failed PRS Workflows

scripts/rare-x/ingest_rarex_dataset.py
RARE-X receives json files for ingest from external source. 
If there is no data to be ingested, an empty json file is deposited in the bucket which breaks the ingest script.
Check for the size of the json to ensure that it is not empty before adding it to list of files to loop through to ingest into dataset.
=> RARE-X: ignore ingest json files with 0 data to ingest into dataset

scripts/bulk_set_requester_pays.sh
https://broadworkbench.atlassian.net/browse/FE-62
This script allows users to set requester pays on/off for multiple workspaces in one command. 
Steps in the script:
1. checks input csv for correct headers and any missing values
2. grants the requester pays SA access to the workspace Google projects
3. authenticates as SA
4. loops through list of workspaces and sets requester pays based on toggle value provided
5. authenticates as user's firecloud account
6. removes SA from workspace Google projects
=> [FE-62] Create bulk-set-requester-pays script

scripts/dragen_reprocessing/get_batch_job_status.py
Gets information like below for each sample: 
```
$ python3 scripts/dragen_reprocessing/get_batch_job_status.py -g gp-cloud-dragen-dev -t test.tsv
INFO: 2024-03-07 14:02:23,337 : Querying for jobs status
INFO: 2024-03-07 14:02:24,920 : Creating test.tsv
To upload tsv to workspace run:
python3 scripts/import_large_tsv/import_large_tsv.py --project <workspace-project> --workspace <workspace_name> --tsv test.tsv
```
tsv inputs looks like
```
entity:sample_id	attempts	latest_status	output_path	last_attempt
fake_project_NA0_v1_WGS_GCP	3	SUCCEEDED	gs://gp-cloud-dragen-dev-output/3_78/aggregation/NA0/2024-02-05-22-33-31	2024-02-06 01:11:02
fake_project_NA12878_v1_WGS_GCP	8	FAILED	gs://fc-236ab095-52ca-4541-bcaa-795635feccd9/repro_output/NA12878/2024-02-01-21-50-25	2024-03-07 15:42:46 …
```
=> Adding get_batch_job_status

scripts/tdr/copy_from_tdr_to_gcs/README.md, scripts/tdr/copy_from_tdr_to_gcs/from_bash_copy_from_tdr.py, scripts/tdr/copy_from_tdr_to_gcs/get_snapshot_files_and_transfer.sh, scripts/tdr/copy_from_tdr_to_gcs/requirements.txt
For [FE-235](https://broadworkbench.atlassian.net/browse/FE-235) we decided that it was best for me to write up pseudo code for this copy from TDR back to an HCA staging bucket /data folder, as no one is currently asking for this, nor is it clear they will.
I have validated this on the command line, but we'll probably want this as a script in the future - as a snapshot can have tens of thousands of data files.
This does *not* reconstitute an entire staging bucket directory structure. It will *only* copy the data files back to staging bucket and is only required while we are still on Dagster and do not yet have support for partial updates [DI-75](https://broadworkbench.atlassian.net/browse/DI-75)
[FE-235]: https://broadworkbench.atlassian.net/browse/FE-235?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVm …
=> FE-235 adding pseudo code doc for copying from TDR to GCS (HCA)

scripts/tdr/copy_from_tdr_to_gcs_hca/README.md, scripts/tdr/copy_from_tdr_to_gcs_hca/copy_from_tdr_to_gcs_hca.py
This PR
- adds a dry run option which produces a count and list of files to be copied which can then be used to confirm with the wranglers before actually copying the files.
- adds a prompt to allow the ignoring of non-empty staging areas. There is often an updated metadata xslx, but it's best to check, so this flags any files that exist so you can verify how to proceed with the wranglers.
- updates the successfully copied counter to be correct.
=> FE-408 - Add dry-run and prompt for non-empty staging areas
