Dockerfile, requirements.txt
1. Added pandas version that is on my local machine - can updated to a different version if needed.
2. The liblzma-dev module was added to the Dockerfile because I kept getting this error:
UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
** The error was resolved after building the Docker with the addition of that module install.
=> requirement pandas and liblzma-dev module in Dockerfile

Dockerfile
1. Added gcsfs to Docker file which will allow reading files from google buckets.
=> add gcsfs (gsutil compatibility) to Dockerfile

scripts/call_monitor_submission_demo.py
https://broadworkbench.atlassian.net/browse/DFE-217
Created a script that will create and launch the Monitor Submission Workflow
08/07/2020
=> [DFE-217] [risk=no] Created Script for Creating and Launching the Monitor Submission Workflow

scripts/monitor_submission.py
Problem statement:
The NeMO team asked for workspace information in the output JSON from our workflow monitoring pipeline.
Solution:
Added workspace information this information to the output JSON created in the Python code.
- Update monitor_submission.py
=> [DFE-237][risk=no] Update monitor_submission

Dockerfile, requirements.txt, scripts/README.md, scripts/terra_service_banner.py
- clean up inputs to take strings for banner fields rather than json banner text; build json in-script
- update some packages and aspects of the docker build so it works
=> modify banner script to run in jenkins

scripts/cdc-sabeti-covid-19/create_data_tables.py
copying the cdc sabeti lab scripts from private horsefish repo to public repo
=> copy cdc-sabeti dir from private repo to public

scripts/van_allen_tools/README.md, scripts/van_allen_tools/set_up_vanallen_workspaces.py, scripts/van_allen_tools/utils.py
1. set bucket creation to us-central1
2. remove authorization domain steps
3. modify OWNER and READER access
4. fix tsv output to have only necessary columns (take out AD cols)
5. set default project to van allen project
6. create readme and utils.py (to be refactored)
Tested by creating two workspaces - success and fail modes.
=> [DFE-441] modify anvil create workspaces script for van allen lab

scripts/van_allen_tools/migrate_van_allen_workspaces.py
- Migrate over entities 
- Check if the entities in both workspaces match
- Migrate over workflow
- Replace data table old bucket path to new bucket path
=> Added copy over data table and workflow, replace data table bucket

scripts/van_allen_tools/migrate_van_allen_workspaces.py, scripts/van_allen_tools/utils.py
- https://broadworkbench.atlassian.net/browse/DFE-474 
- Adding reference data and workspace data to be migrated to the new workspaces
=> Adding reference data and workspace data to be migrate for Van-Allen DFE-474 

scripts/set_requester_pays.sh
- https://broadworkbench.atlassian.net/browse/DFE-506
- https://broadworkbench.atlassian.net/browse/DFE-505
- Change Bucket to take in a string
- Created a while loop to repeat requester pays
=> Change Bucket to take in a string and created a while loop to repeat pays

scripts/mop_workspace/mop_workspace.py
@mmorgantaylor @samanehsan
Here is a PR to add a "time before deletion" argument to the mop script. Note that @mmorgantaylor's notebook will now need to be updated (to include a `weeks_old` argument to all the `mop` calls). 
I'm sorry for all of the whitespace changes, I think I opened it in IntelliJ and that happened automatically. I can strip them back out if that's helpful.
=> Adding number of weeks from creation before a file will be mopped

scripts/tdr/twisttcap/Dockerfile, scripts/tdr/twisttcap/export_pipeline_outputs_to_tdr.py, scripts/tdr/twisttcap/requirements.txt, scripts/tdr/twisttcap/update_docker_image.sh
scripts to support additions to wrapper wdl in warp (PR: https://github.com/broadinstitute/warp/pull/595/files)
=> [DFE-704] add scripts for warp twisttcap wrapper wdl

scripts/terra_service_banner.py
Reverts broadinstitute/horsefish#84
lol there was a permissions bug that I missed when testing 🤦
=> Revert "[SUP-633] Use tmp alerts.json file to create object and set caching metadata in one operation"

scripts/anvil_tdr_ingest/clone_anvil_workspace.py, scripts/anvil_tdr_ingest/utils.py, scripts/emerge/ingest_to_tdr.py
clone source anvil workspace with:
1. notebooks (from dsp-data-ingest/sc_anvil_cmg_ingest_resources)
2. tim schema (from dsp-data-ingest/sc_anvil_cmg_ingest_resources)
3. add source anvil workspace bucket and workspace link as workspace data in cloned workspace
4. add jade SA as reader on cloned workspace
5. copy/maintain and add any new authorization domains
=> update anvil clone script

scripts/set_requester_pays.sh
this PR:
- adds a command line input to set_requester_pays.sh - 'on' or 'off'. it must be specified, i.e. it does not default to 'on'. 
- increases the sleep time from 10 to 15 seconds, since we routinely go through 4-5 rounds of waiting before the permissions kick in
=> [DFE-774] add on/off toggle to requester pays script

scripts/tdr/data_validation/README.md, scripts/tdr/data_validation/validate_tdr_data.py
Context is in DI-78. This is essentially intended to serve as a generic data validation script users can use to validate their TDR datasets and snapshots.
=> DI-78: Validation script and README

scripts/anvil_tdr_ingest/clone_anvil_workspace.py
Updating the path for the resources directory (it is a sub-directory of the ingest_pipeline directory).
=> Update path for resources directory

scripts/wfl/twisttcap/README.md
- add option to specify dataset name instead of uuid
- add auth instructions
=> Update WFL setup README for Twist-TCAP

scripts/anvil_tools/README.md, scripts/anvil_tools/examine_gcs_contents.py
Adding a script that lets you output the contents of 1-2 GCS paths (comparing the output when 2 GCS paths are specified). I'm using this as validation when copying large numbers of files from a deposit bucket to a delivery bucket.
=> Adding script to examine GCS path contents

scripts/set_requester_pays.sh
See ticket for details: https://broadworkbench.atlassian.net/browse/FE-59
=> [FE-59] Update set_requester_pays.sh script to pass a project to bill in the request when disabling RP

scripts/pgs/create_enterics_visualizations_html.py
grouping_col used to be hardcoded to predicted_gambit — this has been fixed
=> fixing grouping_col bug

pipelines/start_dragen/start.wdl
https://gpinfojira.broadinstitute.org/jira/browse/GPLIM-10488
=> RP and output bucket as inputs + adding dragen config creation task 

scripts/dragen_reprocessing/get_dragen_metrics.py
```
$ python3 python/get_dragen_metrics.py -o gs://fc-236ab095-52ca-4541-bcaa-795635feccd9/repro_output/PC83938064/2024-02-20-21-09-54/ -s PC83938064
INFO: 2024-04-03 15:02:07,498 : Reading gs://fc-236ab095-52ca-4541-bcaa-795635feccd9/repro_output/PC83938064/2024-02-20-21-09-54/PC83938064.mapping_metrics.csv
INFO: 2024-04-03 15:02:07,735 : Reading gs://fc-236ab095-52ca-4541-bcaa-795635feccd9/repro_output/PC83938064/2024-02-20-21-09-54/PC83938064.qc-coverage-region-1_coverage_metrics.csv
INFO: 2024-04-03 15:02:07,929 : Reading gs://fc-236ab095-52ca-4541-bcaa-795635feccd9/repro_output/PC83938064/2024-02-20-21-09-54/PC83938064.qc-coverage-region-3_coverage_metrics.csv
INFO: 2024-04-03 15:02:08,130 : Reading gs://fc-236ab095-52ca-4541-bcaa-795635feccd9/repro_output/PC83938064/2024-02-20-21-09- …
```
=> Creating new script to get all needed metrics from dragen output

pipelines/start_dragen/start.wdl
- [GPLIM-10488](https://gpinfojira.broadinstitute.org/jira/browse/GPLIM-10488) - continued WDL updates to add data_type as variable in batch_config.json, so it is no longer hard coded in the file
=> preparing wdl with data_type as config variable

.github/workflows/build_and_push_docker_gen_main.yaml
Had a typo in my tag & push latest for PR to main GH Action.
=> fixed a typo in the build & push latest image GH Action

scripts/workspace_cleanup/delete_clusters.py
One of the scripts we're migrating from the horsefish-private repo needs to be updated - the delete_clusters.py script currently expects the inputs to be V1 workspaces (one billing project for multiple workspaces). The script now takes in one input parameter - a csv file containing a list of cluster IDs and associated Google Project IDs.
=> [FE-311] Make delete_clusters.py script work for V2 workspaces

scripts/tdr/copy_from_tdr_to_gcs_hca/README.md, scripts/tdr/copy_from_tdr_to_gcs_hca/copy_from_tdr_to_gcs_hca.py
We don't want to ask TDR for more than 1000 items at a time, so I added a batch process for getting all items in a request.
=> Added batching for requests to TDR
